LojaImpacta/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LojaImpacta.Models
{
    public class Product
    {
        [Display(Name = "Cód. Produto")]
        [Key]
        public int ProductID { get; set; }

        [Display(Name = "Nome do produto")]
        [StringLength(maximumLength: 30)]
        [Required]
        public string ProductName { get; set; }

        [Display(Name = "URL da Imagem")]
        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; } = "https://th.bing.com/th/id/R.51879f9aeaaf6060aa42a64df71696f1?rik=h8Ox9c2rUwGi%2fg&pid=ImgRaw&r=0";

        [Display(Name = "Preço")]
        [DataType(DataType.Currency)]
        [Required]
        public decimal Price { get; set; }

        [Display(Name = "Descrição do produto")]
        [StringLength(maximumLength: 250)]
        public string? Description { get; set; }

        [Display(Name = "Estoque disponível")]
        [Required]
        public int AmountAvailabel { get; set; } = 0;

    }
}

LojaImpacta/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LojaImpacta.Data;
using LojaImpacta.Models;

namespace LojaImpacta.Controllers
{
    public class ProductsController : Controller
    {
        private readonly LojaImpactaContext _context;

        public ProductsController(LojaImpactaContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {   
            return View(await _context.Product.ToListAsync());
        }

        // GET: Products
        public async Task<IActionResult> IndexFilter(string prodName, int priceRange, string? availableOnly)
        {
            Console.WriteLine($"{prodName}, {priceRange}, {availableOnly}");
            List<Product> allProducts = await _context.Product.ToListAsync();
            ViewData["ProdName"] = prodName;
            ViewData["PriceRange"] = priceRange;
            ViewData["AvailableOnly"] = false;

            if(prodName != null)
            {
                allProducts = allProducts.FindAll(i => i.ProductName.ToUpper().Contains(prodName.ToUpper()));
                ViewData["ProdName"] = prodName;
            }   

            if(priceRange != 0) { 
                ViewData["PriceRange"] = priceRange;
                //1 - priceRange > 1 to 500
                if(priceRange == 1)
                {
                    allProducts = allProducts.FindAll(i => i.Price >= 1 && i.Price <= 500);
                }else if(priceRange == 2)
                //2 - priceRange > 500 to 1500
                {
                    allProducts = allProducts.FindAll(i => i.Price >= 501 && i.Price <= 1500);
                }
                else if(priceRange == 3)
                //3 - priceRange > 1500+
                {
                    allProducts = allProducts.FindAll(i => i.Price >= 1501);
                }
            }
            if(availableOnly == "on")
            {
                ViewData["AvailableOnly"] = true;
                allProducts = allProducts.FindAll(i => i.AmountAvailabel > 0);
            }
            return View(nameof(Index), allProducts);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,ProductName,ImageUrl,Price,Description,AmountAvailabel")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,ProductName,ImageUrl,Price,Description,AmountAvailabel")] Product product)
        {
            if (id != product.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.ProductID == id);
        }
    }
}

LojaImpacta/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LojaImpacta.Data;
using LojaImpacta.Models;

namespace LojaImpacta.Controllers
{
    public class SalesController : Controller
    {
        private readonly LojaImpactaContext _context;

        public SalesController(LojaImpactaContext context)
        {
            _context = context;
        }

        // GET: Sales
        public async Task<IActionResult> Index()
        {
            var allProducts = await _context.Product.ToListAsync();

            ViewData["AllProducts"] = allProducts;

            return View(await _context.Sale.ToListAsync());
        }

        // GET: Sales/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = await _context.Sale
                .FirstOrDefaultAsync(m => m.SaleID == id);

            var prod = await _context.Product.FindAsync(sale.ProductID);
            var salesperson = await _context.User.FindAsync(sale.SalesPersonID);
            var client = await _context.User.FindAsync(sale.ClientID);

            ViewData["ProductInfo"] = $"#{prod.ProductID} | {prod.ProductName}";
            ViewData["Vendedor"] = salesperson.Name;
            ViewData["Cliente"] = client.Name;

            if (sale == null)
            {
                return NotFound();
            }
            
            return View(sale);
        }

        // GET: Sales/Create
        public async Task<IActionResult> Create(int id)
        {
            var prod = await _context.Product.FirstOrDefaultAsync(p => p.ProductID == id);

            var c = await _context.User.ToListAsync();
            var clients = c.FindAll(i => i.AccessLevel == 3);
            SelectList clientsList = new(clients, "UserID", "Name");

            var employees = c.FindAll(i => i.AccessLevel == 1 || i.AccessLevel == 2);
            SelectList employeesList = new(employees, "UserID", "Name");


            ViewData["SelectedProductID"] = prod.ProductID;
            ViewData["SelectedProductName"] = prod.ProductName;
            ViewData["SelectedProductQt"] = prod.AmountAvailabel;
            ViewData["SelectedProductImg"] = prod.ImageUrl;
            ViewData["Clientes"] = clientsList;
            ViewData["Vendedores"] = employeesList;

            return View();
        }

        // POST: Sales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SaleID,SalesPersonID,ClientID,ProductID,AmountBought")] Sale sale, int ProductID)
        {
            if (ModelState.IsValid)
            {
                var prod = await _context.Product.FindAsync(ProductID);
                prod.AmountAvailabel -= sale.AmountBought;
                _context.Product.Update(prod);

                sale.SaleID = Guid.NewGuid();
                sale.ProductID = ProductID;
                sale.FinalPrice = prod.Price * sale.AmountBought;
                sale.SaleDate = DateTime.Now;
                _context.Add(sale);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sale);
        }

        
        // GET: Sales/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = await _context.Sale
                .FirstOrDefaultAsync(m => m.SaleID == id);

            if (sale == null)
            {
                return NotFound();
            }

            var prod = await _context.Product.FindAsync(sale.ProductID);

            var salesperson = await _context.User.FindAsync(sale.SalesPersonID);
            var client = await _context.User.FindAsync(sale.ClientID);

            ViewData["ProductInfo"] = $"#{prod.ProductID} | {prod.ProductName}";
            ViewData["Vendedor"] = salesperson.Name;
            ViewData["Cliente"] = client.Name;

            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var sale = await _context.Sale.FindAsync(id);
            if (sale != null)
            {
                var prod = await _context.Product.FindAsync(sale.ProductID);
                prod.AmountAvailabel += sale.AmountBought;

                _context.Product.Update(prod);

                _context.Sale.Remove(sale);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SaleExists(Guid id)
        {
            return _context.Sale.Any(e => e.SaleID == id);
        }
    }
}

LojaImpacta/Views/Products/Create.cshtml
@model LojaImpacta.Models.Product

@{
    ViewData["Title"] = "Create";
}
<a asp-action="Index" class="btn btn-md btn-outline-none text-dark">
    <i class="bi bi-chevron-compact-left"></i>
    Voltar
</a>
<h1>Criar novo produto</h1>

<hr />
<div class="container">
    <form asp-action="Create" class="row align-items-start">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="col-12 col-md-6">

            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 m-auto col-md-6">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="AmountAvailabel" class="control-label"></label>
                <input asp-for="AmountAvailabel" class="form-control" />
                <span asp-validation-for="AmountAvailabel" class="text-danger"></span>
            </div>
            <div class="form-group text-end">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>

    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LojaImpacta/Views/Products/Delete.cshtml
@model LojaImpacta.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<a asp-action="Index" class="btn btn-md btn-outline-none text-dark">
    <i class="bi bi-chevron-compact-left"></i>
    Voltar
</a>
<h1>Excluir produto</h1>
<h3>Tem certeza que deseja excluir o item abaixo?</h3>
<div>
    <h4>#@Model.ProductID | @Model.ProductName</h4>
    <hr />
    <table class="table table-striped table-responsive">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model=>model.Description)</th>
                <th>@Html.DisplayNameFor(model=>model.Price)</th>
                <th>@Html.DisplayNameFor(model=>model.AmountAvailabel)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Description</td>
                <td>R$@Model.Price</td>
                <td>@Model.AmountAvailabel</td>
            </tr>
        </tbody>
    </table>

    <form asp-action="Delete">
        <input type="submit" value="Excluir produto" class="btn btn-danger" />
    </form>
</div>

LojaImpacta/Views/Products/Details.cshtml
@model LojaImpacta.Models.Product

@{
    ViewData["Title"] = "Details";
}
<a asp-action="Index" class="btn btn-md btn-outline-none text-dark">
    <i class="bi bi-chevron-compact-left"></i>
    Voltar
</a>
<h1>#@Model.ProductID | @Model.ProductName</h1>
<hr />
<div class="container">
    <div class="row">
        <img src="@Model.ImageUrl" class="col-12 col-md-4 mw-100 d-block" />
        <div class="col-12 col-md-8">
            <div class="container">
                <b class="row">
                    Descrição do produto:
                </b>
                <p class="row">
                    @Model.Description
                </p>
            </div>
            <div class="container">
                <b class="row">
                    Preço unitário:
                </b>
                <p class="row">
                    R$@Model.Price
                </p>
            </div>
            <div class="container">
                <b class="row">
                    Qtd. em estoque:
                </b>
                <p class="row">
                    @Model.AmountAvailabel
                </p>
            </div>
            <div class="container">
                <div class="row row-cols-auto">
                    <a asp-action="Create" asp-controller="Sales"
                        asp-route-id="@Model?.ProductID"
                        class="btn btn-lg btn-success"
                    >Comprar</a>
                </div>
            </div>
        </div>
    </div>
</div>
@* 
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AmountAvailabel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AmountAvailabel)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ProductID">Edit</a> |
    <a asp-action="Create" asp-controller="Sales" asp-route-id="@Model?.ProductID">Comprar</a> |
    <a asp-action="Index">Back to List</a>
</div>
 *@

LojaImpacta/Views/Products/Edit.cshtml
@model LojaImpacta.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<a asp-action="Index" class="btn btn-md btn-outline-none text-dark">
    <i class="bi bi-chevron-compact-left"></i>
    Voltar
</a>
<h1>Editar Produto</h1>
<hr />
<div class="container">
    <form asp-action="Edit" class="row align-items-start">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
        <input type="hidden" asp-for="ProductID" />
            
        <div class="col-12 col-md-6">

            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 m-auto col-md-6">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="AmountAvailabel" class="control-label"></label>
                <input asp-for="AmountAvailabel" class="form-control" />
                <span asp-validation-for="AmountAvailabel" class="text-danger"></span>
            </div>
            <div class="form-group text-end">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>

    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LojaImpacta/Views/Products/Index.cshtml
@model IEnumerable<LojaImpacta.Models.Product>

@{
    ViewData["Title"] = "Produtos";

    int priceSelected = -1;
    bool availableOnly = false;
    if(ViewData["AvailableOnly"] != null)
    {
        availableOnly = (bool)ViewData["AvailableOnly"];
    }
    if(ViewData["PriceRange"] != null)
    {
        priceSelected = (int)ViewData["PriceRange"];
    }
}

<h1>Todos os produtos</h1>

<p>
    <a asp-action="Create" class="btn btn-md btn-outline-light text-dark">Adicionar novo produto</a>
</p>

<div class="container">
    <form asp-action="IndexFilter" method="get" class="row mb-3 justify-content-between">
        <div class="col-12 col-md-4">
            <input name="prodName" value="@(ViewData["ProdName"])" type="text" class="form-control" placeholder="Pesquisar pelo nome..." />
        </div>
       
        <div class="col-6 col-md-3">

            <select name="priceRange" class="form-select">
                <option selected="@(priceSelected==0)" value="0">Todos os preços</option>
                <option selected="@(priceSelected==1)" value="1">R$1-R$500</option>
                <option selected="@(priceSelected==2)" value="2">R$500-R$1500</option>
                <option selected="@(priceSelected==3)" value="3">R$1500+</option>
            </select>
        </div>
        <div class="col-6 col-md-3">
            <label class="form-label">Apenas disponíveis</label>
            <input name="availableOnly" type="radio" checked="@(availableOnly)" />
        </div>
        <div class="col-12 m-auto col-md-2 m-md-0">
            <a asp-action="Index" class="btn btn-sm btn-outline-none text-dark">Limpar</a>
            <input type="submit" value="Filtrar" class="btn btn-sm btn-success" /> 
        </div>
    </form>
    <div class="row row-cols-lg-4 row-cols-3 gap-5">
        @if(Model.Count() == 0)
        {
            <div class="container mt-5">
                <div class="row text-center">
                    <h2>Não há produtos com essas especificações.</h2>
                </div>
            </div>
        }
        @foreach(var item in Model)
        {
            <div class="card">
                <img src="@item.ImageUrl" class="d-block h-50 object-cover" alt="@item.ProductName" />
                <div class="card-body">
                    <h5 class="card-title">@item.ProductName</h5>
                    <p class="card-text text-truncate">@item.Description</p>
                    <p class="lead">R$@item.Price</p>
                    <a asp-action="Details" asp-controller="Products"
                        asp-route-id="@item.ProductID"
                        class="btn btn-lg btn-success">Comprar</a>
                    <div class="container p-0">
                        <a asp-action="Edit" asp-controller="Products"
                            asp-route-id="@item.ProductID"
                            class="btn btn-sm btn-outline-none text-dark">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a asp-action="Delete" asp-controller="Products"
                             asp-route-id="@item.ProductID"
                             class="btn btn-sm btn-outline-none text-danger">
                            <i class="bi bi-trash"></i>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>